builds:
- main: .
  ldflags: 
    - -s -w
    - -X github.com/kekeniker/marco/pkg/version.Version={{.Tag}}
  goos:
  - linux
  - darwin
  - windows
brews:
  - tap:
      owner: kekeniker
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/kekeniker/marco/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    folder: Formula
    description: "Marco is a CLI tool for showing Spinnaker application, pipelines and pipeline templates"
    homepage: "https://github.com/kekeniker/marco"
    test: |
      system "#{bin}/marco --version"
