version: 2.1

executors:
  default:
    working_directory: /go/src/github.com/KeisukeYamashita/marco
    docker:
      - image: circleci/golang:1.15
        environment:
          GO111MODULE: "on"

jobs:
  release:
    executor: default
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.*)*/
